[phases.setup]
nixPkgs = ["python311"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd backend"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
